apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: bookstore-microservices
data:
  PORT: "80"
  DB_HOST: postgres
  DB_PORT: "5432"
  DB_USER: bookstore
  DB_PASSWORD: bookstore
  DB_NAME: payment
  JWT_SIGNING_KEY: 601304E0-8AD4-40B0-BD51-0B432DC47461
  SECURITY_URL: http://security
  WAREHOUSE_URL: http://warehouse
  OAUTH_CLIENT_ID: payment
  OAUTH_CLIENT_SECRET: payment_secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: bookstore-microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      serviceAccountName: book-admin
      containers:
        - name: payment
          image: bookstore/payment:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: payment-config
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: bookstore-microservices
spec:
  selector:
    app: payment
  ports:
    - port: 80
      targetPort: 80
