apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookstore-microservices
resources:
  - 00-namespace-rbac.yaml
  - 01-postgres.yaml
  - 02-account.yaml
  - 03-security.yaml
  - 04-warehouse.yaml
  - 05-payment.yaml
  - 06-gateway.yaml
  - 07-web.yaml
